[package]
name = "fox-binary"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "FOX binary format parsers: PE, ELF, Mach-O"

[dependencies]
fox-core.workspace = true
fox-arch.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
log.workspace = true
